In [73]:
import pandas as pd
from toxic_funcs import Cleaner
import numpy as np

In [74]:
#reading only first n for testing purposes
n = 10000
df = pd.read_csv("data/train.csv").set_index('id')
df = df.head(n)

## Preprocess

In [75]:
#running through the custom cleaner

clean_comments = []
for comment in df.comment_text.values:
    clean_comments.append(Cleaner(comment))


In [76]:
#slapping it onto df

df['cleaned'] = clean_comments

In [77]:
from keras.preprocessing.text import Tokenizer
#split texts into words

tokenizer = Tokenizer(num_words = 10000)

In [78]:
#
tokenizer.fit_on_texts(df.cleaned.values)

In [79]:
tokenized = tokenizer.texts_to_matrix(df.cleaned.values)

In [80]:
df

comment_text  toxic  \
id                                                                           
0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   
00025465d4725e87  "\n\nCongratulations from me as well, use the ...      0   
0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK      1   
00031b1e95af7921  Your vandalism to the Matt Shirvington article...      0   
00037261f536c51d  Sorry if the word 'nonsense' was offensive to ...      0   
00040093b2687caa  alignment on this subject and which are contra...      0   
0005300084f90edc  "\nFair use rationale for Image:Wonju.jpg\n\nT...      0   
00054a5e18b50dd4  bbq \n\nbe a man and lets discuss it-maybe ove...      0   
0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......      1   
0006f16e4e9f292e  Before you start throwing accusations and warn...      0   
00070ef96486d6f9  Oh, and the girl above started her arguments w...      0   
00078f8ce7eb276d  "\n\nJuelz Santanas Age\n\nIn 2002, Juelz Sant...      0   
0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...      1   
000897889268bc93   REDIRECT Talk:Voydan Pop Georgiev- Chernodrinski      0   
0009801bd85e5806  The Mitsurugi point made no sense - why not ar...      0   
0009eaea3325de8c  Don't mean to bother you \n\nI see that you're...      0   
000b08c464718505  "\n\n Regarding your recent edits \n\nOnce aga...      0   
000bfd0867774845  "\nGood to know. About me, yeah, I'm studying ...      0   
000c0dfd995809fa  "\n\n Snowflakes are NOT always symmetrical! \...      0   
000c6a3f0cd3ba8e  "\n\n The Signpost: 24 September 2012 \n\n Rea...      0   
000cfee90f50d471  "\n\nRe-considering 1st paragraph edit?\nI don...      0   
000eefc67a2c930f  Radial symmetry \n\nSeveral now extinct lineag...      0   
000f35deef84dc4a  There's no need to apologize. A Wikipedia arti...      0   
000ffab30195c5e1  Yes, because the mother of the child in the ca...      0   
0010307a3a50a353  "\nOk. But it will take a bit of work but I ca...      0   
0010833a96e1f886  "== A barnstar for you! ==\n\n  The Real Life ...      0   
...                                                             ...    ...   
1a66218abe1e690a  "It is interesting that although you state abo...      0   
1a67395d931587cd  And I GAVE you people sources, and that still ...      0   
1a67a4f7d445746c  "\n\nYour accustations towards ArcAngel\n\nYou...      0   
1a682782dc659340  KO\n\nIf you avoid violating the 3RR Rule and ...      0   
1a6930de0c90c08b                   Treaty of Peace with Italy, 1947      0   
1a6a64e250b7ae53  "\n\n Edit summary \n\nWhen editing an article...      0   
1a6d0771a0b3f861  "\n\n  and his otters • (Broken clamshells • O...      0   
1a6d4a912002da85  The US did not fight at 2nd battle of El Alamein!      0   
1a6d8e02d7fe85a3  "\n\nChat\nHi XLR8TION, thanks for adding the ...      0   
1a6dd54e3578a98f  Dungeon Hunter 5\nHey just asking why did you ...      0   
1a6e9383dfe0ba11  Sanskrit  suzI & {suzIka} a. splendid, beautif...      0   
1a6f5379db374ab5  "\nI was surprised at the speedy launching of ...      0   
1a6ff1035b60dc34  What's going on here? \n\nThis paragraph in th...      0   
1a700eab31f77b38  So not a rip-off \n\nThis is, like, the best b...      0   
1a7078b585a55d89  (Shakes His Head)\n\nIt's not freaking incorre...      0   
1a71635e4e8e91f6                              here in my last edits      0   
1a72e2ac84094285  "\n\n .\n\nLook i went on the bbc sport websit...      0   
1a733d7c2fcf23dd  February 2006 (UTC)\n\nHey, look, it's that im...      0   
1a73cbb713474ffc  How terrible that it was there all along, just...      0   

# Build labels and features

In [81]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X = tokenized
y = np.dstack((df.toxic.values, df.severe_toxic.values, df.obscene.values, df.threat.values, df.insult.values , df.identity_hate.values))[0]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1) #stratify fails with low valued categories
'''X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)'''


'X_scaler = StandardScaler().fit(X_train)\nX_train_scaled = X_scaler.transform(X_train)\nX_test_scaled = X_scaler.transform(X_test)'

In [82]:
print(f"x-{X_train.shape} y-{y_train.shape}")
y_train

x-(7500, 10000) y-(7500, 6)


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       ..., 
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# Build model

In [133]:
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Dropout

# Create a Neural Network model here
# YOUR CODE HERE
model = Sequential()
model.add(Dense(100, activation = "relu", input_dim = X_train.shape[1]))
model.add(Dense(50,activation = "relu"))
model.add(Dropout(.1))
model.add(Dense(10, activation = "relu"))
model.add(Dense(y_train.shape[1], activation = "sigmoid"))

In [134]:
model.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

model.fit(X_train, y_train, epochs = 4, verbose=1)

Epoch 1/4
7500/7500 [==============================] - 32s 4ms/step - loss: 0.2167 - acc: 0.9453
Epoch 2/4
7500/7500 [==============================] - 24s 3ms/step - loss: 0.0812 - acc: 0.9684
Epoch 3/4
7500/7500 [==============================] - 29s 4ms/step - loss: 0.0467 - acc: 0.9824
Epoch 4/4
7500/7500 [==============================] - 33s 4ms/step - loss: 0.0285 - acc: 0.9889


In [135]:
model_loss, model_accuracy = model.evaluate(X_test, y_test, verbose=2)
print(f"Normal Neural Network Test - Loss: {model_loss}, Accuracy: {model_accuracy}")

Normal Neural Network Test - Loss: 0.09396917509585619, Accuracy: 0.9790666664123535


In [136]:
#model.save("models/vanilla.h5")

In [137]:
#from keras.models import load_model
#model = load_model('models/vanilla.h5')

In [138]:
dummy = df[df.threat == 1]
dummy[dummy.toxic == 0].comment_text.values

array([ 'Please stop. If you continue to ignore our policies by introducing inappropriate pages to Wikipedia, you will be blocked.',
       '"\n\n Lock Down \n\nI don\'t know about the ""Bulgarian BULLSHIT season"", but don\'t be fooled from where exactly i connect. If i see you editing, or someone else you send, the DDA40X article one more time, you will spend the next few years in prison. I will arrange you a meeting with certain people for suspicions of terrorism. Yes. I can do that. A terror suspect nowadays, you can kiss your young life goodbye. If you file complaints and i\'m banned, you and your naked ass will have the whole time in the world, in the cell block, to think what went wrong. 87.252.167.254  "'], dtype=object)

In [128]:
count = 0
for index, row in df.head(10000).iterrows():
    pred = model.predict(tokenizer.texts_to_matrix([row.cleaned]))[0][3]
    if pred <= .25 and row.obscene == 1:
        count += 1
        print(f"{index} - pred: {pred}  - act: {row.toxic}")
        print
        print(row.cleaned)
        print('=================================')
        

0002bcb3da6cb337 - pred: 0.006563019473105669  - act: 1
cocksucker before you piss around on my work
001810bf8c45bf5f - pred: 0.0038192574866116047  - act: 1
you are gay or antisemmitian.  archangel white tiger.  meow.  greetingshhh.  uh there are two ways why you do erased my comment about ww that holocaust was brutally slaying of jews and not gaysgypsysslavsanyone.     if you are anti semitian than shave your head bald and go to the skinhead meetings.     if you doubt words of the bible that homosexuality is a deadly sin make a pentagram tatoo on your forehead go to the satanistic masses with your gay pals.     first and last warning you fucking gay   i wont appreciate if any more nazi shwain would write in my page.  i dont wish to talk to you anymore.  beware of the dark side. 
00190820581d90ce - pred: 0.015031005255877972  - act: 1
fuck your filthy mother in the ass dry. 
001dc38a83d420cf - pred: 0.00016947797848843038  - act: 1
get fucked up. get fuckeeed up.  got a drink that you

015c99386399aa14 - pred: 0.003060882678255439  - act: 1
hello how do i get somebody to fix shit around here. 
015d1b0bb4cc744d - pred: 0.0009910938097164035  - act: 1
dictionaries.  how dare you call my contribution spam.   i am a kurd and i made a lsit of kurdish dictionaries. you bloody turkish nationalist and atoricity commiting bone breaking nazi. watch out folk this slimy turk is trying to censor the internet this is not undemocratic turkey here no prison cells in wikipedia you stupid turk.  and you buggers want membership to the eec
01625cc84c6ef15b - pred: 0.05685186758637428  - act: 0
how do you know he is dead.  its just his plane that crashed.  jeezz quit busting his nuts folks.
018663f910e0bfe6 - pred: 0.027086028829216957  - act: 1
what a motherfucking piece of crap those fuckheads for blocking us. 
019ab9a91e7fcdbe - pred: 0.06318068504333496  - act: 1
are you fucker mother fucker have nothing to do but block university computers. go and suck cocks
019c4ce48e6bfbab - pred:

02e6fc74d370b880 - pred: 0.01872221939265728  - act: 1
.  how about this go fuck yourself.
03088aacc4600323 - pred: 0.13198816776275635  - act: 1
fuck you faggot i dont care if i get blocked as long as everyone knows you are a dumb cunt.
030ed098f411f8c7 - pred: 0.022078728303313255  - act: 1
cavorting with heretics .  fuck heretics.  
03222bc65ab17f08 - pred: 0.11504607647657394  - act: 1
this is your dad sam .  im worried about you.  worried that your cock wont fit in my ass anymore.  omfk lolz haha i said peeenis gorf gorf gorf gorf
033d6574ecbbeb8e - pred: 0.00944290217012167  - act: 1
or any historical fact concerning current armenia pertaining wikiprojects.  keep your pathetic winking marks to your antiturkish ass.
034beefa865b5381 - pred: 0.009656609036028385  - act: 1
i have a dick its bigger than yours.  hahaha
034cf319ae8fab24 - pred: 0.0026284914929419756  - act: 1
watch out for user:xeno hell bite your dick off.  
0350c82d1f207e0e - pred: 0.0027404276188462973  - act: 0
ble

04aadd2f732eef57 - pred: 0.0011132697109133005  - act: 1
hey idiot. im simply verifying the truth. mobile was not the first to have a ringtone maker online.  brinked was. do some fucking research before you remove my shit. tired of you assholes removing my hard work im putting into making wikipedia a relevant page.
04ac56a43d2d209a - pred: 0.0035656674299389124  - act: 1
re: .  punk ass snitch get the cock.
04af185d298b513f - pred: 9.596497693564743e-05  - act: 1
.  oh right like this article sucks and you know it. isnt abusive language. hypocrite. eat shit and die loser.
04cf14506adaaf42 - pred: 0.005849784705787897  - act: 1
you are a faggot. get a life 
04f8cad9735b8c3c - pred: 0.0031837723217904568  - act: 1
recent.  you just a pussy.
050c330758a40c44 - pred: 1.327502559433924e-05  - act: 0
 reliable sources   . cheating:. barry bonds:cheater from cbs yea i kinda think that is reliable.  dear barry bonds you are either an outright cheater or very stupid from the usa today . yes bar

056d37c3ad166da3 - pred: 0.0006219728966243565  - act: 1
.   a kitten for you.  just becuz ur pussy  lying.  
057894cf4738a5d8 - pred: 0.08566970378160477  - act: 1
you are a gay homo. i hope you choke on your penis and die. i am sending a big bleck guy to jizz in your face.
0593a8a738fedf41 - pred: 0.044838111847639084  - act: 1
igho otegheri deletion. who the hell are you to decide what to delete and what not.  you could go fuck yourself u little piece of shit. 
05a928e4d2101d4e - pred: 0.029704269021749496  - act: 1
: nobody cares about the fucking shit like you fucking bitch.  
05bde2e257e74eca - pred: 0.002669157460331917  - act: 1
the only thing you are persistant at you ugly bastard is fucking the troll
05ca1ec519e6efb0 - pred: 0.0005450408207252622  - act: 1
fuck you .  muthafucka   you jerk you scum lowlife loser .   hehe hahah
05d2bc5c9264fb4f - pred: 3.0263915959949372e-06  - act: 1
look you little cocksucker. i did nothing wrong. i am sick of your bullshit harassment and yo

065ed7f6fcb56b44 - pred: 0.08594487607479095  - act: 1
.  why dont you remove my free speech you goddamned self you whiny little pipsquak. thats all you seem to be good at doing.
06611b9bcca6dfd3 - pred: 0.0859065055847168  - act: 1
go kill yourself .  you should be ashamed of yourself. twoofers like you are scumbags that deserve to die. you anti scientific assholes are destroying america.
0661f992b32b3351 - pred: 0.07593873143196106  - act: 1
fuck of nazi propaganda. odpierdalcie sie jebani faszyści od polski .  
06678c919e830854 - pred: 0.009273295290768147  - act: 1
since this is my user page i can say what i want:.  you guys are all a bunch of motherfucking ass eaters and i hope you all rot in hell.
067198818b52b9dc - pred: 0.0012449802597984672  - act: 1
.   you are an awesome wikipedian .    some shit some droppings of filthy muck mess to feel you better. dont bother myself    summon 
067c5e814e88a56b - pred: 0.0267590694129467  - act: 1
fuck you u useless bot fuck you u useless 

06f0b97018548ab9 - pred: 0.0009024863829836249  - act: 0
jd the sock fiend .  now hes lying out his ass on the ani page but i cant comment. and no im not this mrth person im just me.
0700b07700927977 - pred: 0.05716188624501228  - act: 1
smallthingy.  are you gay.  do you frequent the hellfire club.  do you shake your little tusch on the catwalk. 
0700ee9d51b55d33 - pred: 0.10569074004888535  - act: 1
william s saturn is a sockpuppet .  hey dickweed saturn remember me.   you dumb fat bitch
07103155fc2836a4 - pred: 0.003638260532170534  - act: 1
fuck off i do what i want.
071dc9bda006e62c - pred: 0.004474674817174673  - act: 1
handing out blocks using twinkle. what a fucking disgrace.   lfdder
0727629762034159 - pred: 0.12682552635669708  - act: 1
no think o it this way im doing all that same shit youve been doing to me okay also ill let them merge if youd stop getting rid of my stff and apologize and get rid of that shit tryna get rid of my page and also go to hell
0735c7334d85c6aa - p

089b68589c99b69d - pred: 0.15283972024917603  - act: 1
did i hurt your feelings.  its okay you can ban me i will create a new account and sign in from a different ip. i must have hurt your feelings pretty bad.  douche bag.
089e6f0cdf57c9f2 - pred: 9.096671419683844e-06  - act: 1
.   that wasnt nice .  i am reposting this to piss off tbhotch. enjoy you dumb piece of shit. have fun being jobless. soon teachers that think too highly of themselves wont be a problem in this country anymore. and if youre going to run around tossing threats because youre too fucking stupid to accept reality instead of getting into a flame war over demographics pissing off an entire base then save yourself the trouble of throwing around even more threats and just ban me like you dumb public school pieces of dog shit wiki editors keep threatening over and over again. just make sure you have every vpn and spoof address banned also or youre just going to be wasting your time.  oh and;.  its people like you that m

09bbd54cf7f5ecd9 - pred: 0.0010408738162368536  - act: 1
damn wiki admins .  what is it with all these wiki admins and them not being able to follow rules and policies such as the npov rr and rules pertaining for vandalism.  if anyone knows how i can get in touch directly with senior admins i would greatly appreciate it as some admins just make their owns rules up on the spot while disobeying wikipedias rules and effectivly slamming banhammers.  and no im not talking about all admins but i am talking about quite a few admins. 
09e42c1742c9a50c - pred: 0.053232982754707336  - act: 1
but ew .  he was a fαg which is against nature and is the most disgusting thing. youre not a woman are you.  sexism is wrong. being wrong is for women.
09e8e8ad3963d537 - pred: 0.029972324147820473  - act: 1
angry .  fuck you bitch
09f281221f4a8bec - pred: 0.0008180300355888903  - act: 1
right its less selective you stupid fuck
0a1b9d1dc60b0ea6 - pred: 0.002647626446560025  - act: 1
stop pussy footing . ban 

0b463a6fa3e34c3f - pred: 0.001863138284534216  - act: 1
edit request from     .  mauler is a shit faggot .  
0b491d7d15af9b7d - pred: 0.0005488222232088447  - act: 1
it is pronouced rink in you moron.  not rincon like it should be in spanish.   wtoc always says rink in this rink in that.  go fuck yourself.  this edit is correct you gd mf sob.
0b56f5e4691568e4 - pred: 0.027025938034057617  - act: 1
faggot .  faggot .  faggot .  faggot
0b625cb49744edbc - pred: 8.547683682991192e-05  - act: 1
youre a pathetic bureaucratic piece of slime. you can remove your withered ballsack with a rusty shears.  or you can eat my shit. your name will be on the syph list one day with a †.
0b649be53b494a8a - pred: 0.002011900069192052  - act: 1
hold on.  ive got something to say to u. fuk u.   yea thats right u r gay for revertin my edit you dumb fuk.  lol go .  fuk urself you gay cock licker haha
0b6cad7b53610a5c - pred: 0.0015821531414985657  - act: 1
bite me .  youre a dickhead drop dead  
0b6f5024a35d9

0c0e9e001b1d82cf - pred: 0.05140317976474762  - act: 1
gay sex  .  demiurge loves it in his irish ass.
0c13eab75027d59b - pred: 0.03516045957803726  - act: 1
listen dumbass i didnt do any anything to the pelycosaur page so fuck you you cunt gluzing asswipe
0c28b272e80ec36b - pred: 0.00040142607758753  - act: 1
my page aaa .  your just a mean old bullshitting fart. as you would put it
0c2b0d517e954dfa - pred: 0.01871219277381897  - act: 0
schtippdick .  you. you boy. youuuuuu. terisoaio.  yeah. yeah. yeah. yeah. yeah. yeah. yeah. yeah. yeah. yeah. yeah. yeah. yeah. yeah. yeah. yeah. yeah.
0c31b95015167c1d - pred: 0.19937679171562195  - act: 0
i refer to peoples constantly taking the words of jimbo as policy the idea of removing any userbox with a political point of view is his point of view.  thats at the core of this problem you did not notice that an admin skipped over the tfd process and speedied something when there is no rule explicitly against having an opinion in a userbox.   rat

0c888087108ada34 - pred: 0.05254006013274193  - act: 1
ekgograf and his son of bitch of gang of dumb n*zi  and are the greatest batard that ever walk on earth .  
0c954ebf2fa4c16f - pred: 0.0008972847717814147  - act: 1
go masturbate yourself on someone elses page you will get no satisfaction from me slut.  wikipedia is not the proper place for you to abuse your powers just because youre unsatisfied in life.  it aint my fault youre ugly sista.
0cb38172f1b992d9 - pred: 0.00019128707936033607  - act: 1
it is not a tko you idiot.  you have no idea what it is and its a swinging neckbreaker you very unsmart and very unclever faggotgot it.  dark hooded smoker
0cd29f52aebb4750 - pred: 0.07267721742391586  - act: 1
yo btch.  you absolute fukng little btch you wanna step up face to face toe to toe you fukng absolute tiny little fukng hopeless btch. 
0cf3cb7aa0e6cb40 - pred: 0.00019563062232919037  - act: 1
my balls .  big balls.   ive got big balls youve got big balls shes got big balls .   the

KeyboardInterrupt: 

In [127]:
tot = df[df.toxic == 1].count()[0]
count/tot*100

0.0

In [175]:
pathetic, crybaby, pimping, meagre, retard
pussy
homo

35

In [187]:
y_train

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       ..., 
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.]])

In [23]:
from keras.datasets import reuters

In [25]:
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=1000,
                                                         test_split=0.2)

2113536/2110848 [==============================] - 1s 0us/step


In [30]:
y_train[0]

array([ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [146]:
for index, row in enumerate(y):
    if row[0] == 1 and row[2] == 1: print(index)

79
176
600
802
1017
1085
1312
1535
1878
2018
2373
2485
2894
2915
3029
3884
4712
4733
4888
5397
5569
5934
6613
6695
7145
7299
7818
8305
8976
8979
9650


In [129]:
y[9650]

array([1, 0, 1, 1, 0, 0])

In [130]:
test = model.predict(tokenizer.texts_to_matrix([df.iloc[9650].cleaned]))
test[0]

array([ 0.23637296,  0.15775938,  0.16884488,  0.14224239,  0.1462013 ,
        0.14857912], dtype=float32)

In [131]:
test.max()

0.23637296

In [132]:
top = test.max()

if top > .1:
    for cat in test[0]:
        if ((cat*1.5) > top):
            print('1, ', end = '')
        else: print('0, ', end = '')
        

1, 1, 1, 0, 0, 0, 