In [1]:
import pandas as pd
from toxic_funcs import Cleaner
import numpy as np

In [3]:
#reading only first n for testing purposes
n = 10000
df = pd.read_csv("data/train.csv").set_index('id')
df = df.head(n)

## Preprocess

In [4]:
#running through the custom cleaner

clean_comments = []
for comment in df.comment_text.values:
    clean_comments.append(Cleaner(comment))


In [5]:
#slapping it onto df

df['cleaned'] = clean_comments

In [7]:
from keras.preprocessing.text import Tokenizer
#split texts into words

tokenizer = Tokenizer(num_words = 10000)

In [8]:
#
tokenizer.fit_on_texts(df.cleaned.values)

In [9]:
tokenized = tokenizer.texts_to_matrix(df.cleaned.values)

In [10]:
tokenizer

In [11]:
df

comment_text  toxic  \
id                                                                           
0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   
00025465d4725e87  "\n\nCongratulations from me as well, use the ...      0   
0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK      1   
00031b1e95af7921  Your vandalism to the Matt Shirvington article...      0   
00037261f536c51d  Sorry if the word 'nonsense' was offensive to ...      0   
00040093b2687caa  alignment on this subject and which are contra...      0   
0005300084f90edc  "\nFair use rationale for Image:Wonju.jpg\n\nT...      0   
00054a5e18b50dd4  bbq \n\nbe a man and lets discuss it-maybe ove...      0   
0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......      1   
0006f16e4e9f292e  Before you start throwing accusations and warn...      0   
00070ef96486d6f9  Oh, and the girl above started her arguments w...      0   
00078f8ce7eb276d  "\n\nJuelz Santanas Age\n\nIn 2002, Juelz Sant...      0   
0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...      1   
000897889268bc93   REDIRECT Talk:Voydan Pop Georgiev- Chernodrinski      0   
0009801bd85e5806  The Mitsurugi point made no sense - why not ar...      0   
0009eaea3325de8c  Don't mean to bother you \n\nI see that you're...      0   
000b08c464718505  "\n\n Regarding your recent edits \n\nOnce aga...      0   
000bfd0867774845  "\nGood to know. About me, yeah, I'm studying ...      0   
000c0dfd995809fa  "\n\n Snowflakes are NOT always symmetrical! \...      0   
000c6a3f0cd3ba8e  "\n\n The Signpost: 24 September 2012 \n\n Rea...      0   
000cfee90f50d471  "\n\nRe-considering 1st paragraph edit?\nI don...      0   
000eefc67a2c930f  Radial symmetry \n\nSeveral now extinct lineag...      0   
000f35deef84dc4a  There's no need to apologize. A Wikipedia arti...      0   
000ffab30195c5e1  Yes, because the mother of the child in the ca...      0   
0010307a3a50a353  "\nOk. But it will take a bit of work but I ca...      0   
0010833a96e1f886  "== A barnstar for you! ==\n\n  The Real Life ...      0   
...                                                             ...    ...   
1a66218abe1e690a  "It is interesting that although you state abo...      0   
1a67395d931587cd  And I GAVE you people sources, and that still ...      0   
1a67a4f7d445746c  "\n\nYour accustations towards ArcAngel\n\nYou...      0   
1a682782dc659340  KO\n\nIf you avoid violating the 3RR Rule and ...      0   
1a6930de0c90c08b                   Treaty of Peace with Italy, 1947      0   
1a6a64e250b7ae53  "\n\n Edit summary \n\nWhen editing an article...      0   
1a6d0771a0b3f861  "\n\n  and his otters • (Broken clamshells • O...      0   
1a6d4a912002da85  The US did not fight at 2nd battle of El Alamein!      0   
1a6d8e02d7fe85a3  "\n\nChat\nHi XLR8TION, thanks for adding the ...      0   
1a6dd54e3578a98f  Dungeon Hunter 5\nHey just asking why did you ...      0   
1a6e9383dfe0ba11  Sanskrit  suzI & {suzIka} a. splendid, beautif...      0   
1a6f5379db374ab5  "\nI was surprised at the speedy launching of ...      0   
1a6ff1035b60dc34  What's going on here? \n\nThis paragraph in th...      0   
1a700eab31f77b38  So not a rip-off \n\nThis is, like, the best b...      0   
1a7078b585a55d89  (Shakes His Head)\n\nIt's not freaking incorre...      0   
1a71635e4e8e91f6                              here in my last edits      0   
1a72e2ac84094285  "\n\n .\n\nLook i went on the bbc sport websit...      0   
1a733d7c2fcf23dd  February 2006 (UTC)\n\nHey, look, it's that im...      0   
1a73cbb713474ffc  How terrible that it was there all along, just...      0   

# Build labels and features

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X = tokenized
y = to_categorical(np.array(df.identity_hate))

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
'''X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)'''


'X_scaler = StandardScaler().fit(X_train)\nX_train_scaled = X_scaler.transform(X_train)\nX_test_scaled = X_scaler.transform(X_test)'

In [13]:


'''y = []
for item in dummy:
    y.append([item])
y = np.array(y)
y.reshape(-1,1)'''
X_train

array([[ 0.,  1.,  1., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [ 0.,  1.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  1.,  1., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.]])

In [14]:
print(f"x-{X_train.shape} y-{y_train.shape}")

x-(7500, 10000) y-(7500, 2)


# Build model

In [15]:
from keras.models import Sequential
from keras.layers import Dense

# Create a Neural Network model here
# YOUR CODE HERE
model = Sequential()
model.add(Dense(500,activation = "relu", input_dim = 10000))
model.add(Dense(70, activation = "relu"))
model.add(Dense(2, activation = "softmax"))

In [17]:
model.compile(
    optimizer = 'adam',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)
model.fit(X_train, y_train, epochs = 3, verbose=1)

Epoch 1/3
7500/7500 [==============================] - 90s 12ms/step - loss: 0.0674 - acc: 0.9916
Epoch 2/3
7500/7500 [==============================] - 93s 12ms/step - loss: 0.0199 - acc: 0.9941
Epoch 3/3
7500/7500 [==============================] - 118s 16ms/step - loss: 0.0079 - acc: 0.9985


In [18]:
model_loss, model_accuracy = model.evaluate(X_test, y_test, verbose=2)
print(f"Normal Neural Network Test - Loss: {model_loss}, Accuracy: {model_accuracy}")

Normal Neural Network Test - Loss: 0.06462268334236287, Accuracy: 0.9884


In [89]:
#model.save("models/vanilla.h5")

In [116]:
from keras.models import load_model
model = load_model('models/vanilla.h5')

In [123]:
dummy = df[df.threat == 1]
dummy[dummy.toxic == 0].comment_text.values

array([ 'Please stop. If you continue to ignore our policies by introducing inappropriate pages to Wikipedia, you will be blocked.',
       '"\n\n Lock Down \n\nI don\'t know about the ""Bulgarian BULLSHIT season"", but don\'t be fooled from where exactly i connect. If i see you editing, or someone else you send, the DDA40X article one more time, you will spend the next few years in prison. I will arrange you a meeting with certain people for suspicions of terrorism. Yes. I can do that. A terror suspect nowadays, you can kiss your young life goodbye. If you file complaints and i\'m banned, you and your naked ass will have the whole time in the world, in the cell block, to think what went wrong. 87.252.167.254  "'], dtype=object)

64

In [143]:
df[df.cleaned.isin('fuck')]

TypeError: only list-like objects are allowed to be passed to isin(), you passed a [str]

In [32]:
count = 0
for index, row in df.head(10000).iterrows():
    pred = round(model.predict(tokenizer.texts_to_matrix([row.cleaned]))[0][1],0)
    if int(pred) != wrow.identity_hate and row.identity_hate == 1:
        count += 1
        print(f"{index} - pred: {pred}  - act: {row.toxic}")
        print
        print(row.cleaned)
        print('=================================')


00472b8e2d38d1ea - pred: 0.0  - act: 1
a pair of jew hating weiner nazi schmucks.
01166f26ee280e56 - pred: 0.0  - act: 1
gay .  the existence of cdvf is further proof that  is a sad twat. he is also very ugly and has a willy for a face.
015d1b0bb4cc744d - pred: 0.0  - act: 1
dictionaries.  how dare you call my contribution spam.   i am a kurd and i made a lsit of kurdish dictionaries. you bloody turkish nationalist and atoricity commiting bone breaking nazi. watch out folk this slimy turk is trying to censor the internet this is not undemocratic turkey here no prison cells in wikipedia you stupid turk.  and you buggers want membership to the eec
02c6e41e4b317ac3 - pred: 0.0  - act: 1
wouldnt be the first time bitch. fuck you ill find out where you live sodomize your wife and then burn your house down. fuck you you fucking queer.
031be7991d883341 - pred: 0.0  - act: 1
hey you freaking hermaphrodite.  please unprotect your user page; i would like to move it to a more suitable title or th

0daadaa11dffa075 - pred: 0.0  - act: 1
gays are disgusting.  its just my opinion but gays are disgusting.
12c82a67010c0fcf - pred: 0.0  - act: 0
.  an illness has nothing to do with timeera but mental illnesses for some reason do. in a society where everyone is narcissistic its not a disorder. ragheads think were insane and we think those sand niggers are crazy too. ever heard of einsteins theory of relativity.  i think not. 
15020e13393c4b3c - pred: 0.0  - act: 1
hi you poor twerps. my money does far more good than your pathetic rule enforcing. have fun with your fat wives and gay hookers.
156f84c4b9052ca5 - pred: 0.0  - act: 1
hey white person you suck. stop being so white. nigger pride.   (non white person)
16a4d34345378025 - pred: 0.0  - act: 1
hey queer andrew.  stop messing around. is your mum lesbian and father homosexual. 


In [33]:
tot = df[df.toxic == 1].count()[0]
count/tot*100

1.956745623069001

35

In [187]:
y_train

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       ..., 
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.]])

In [39]:
tokenizer.texts_to_sequences(['fag'])

[[3091]]

In [38]:
tokenizer.texts_to_matrix([df.loc['02c6e41e4b317ac3'].cleaned])

array([[ 0.,  1.,  0., ...,  0.,  0.,  0.]])

# 